apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: model:latest
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
          - sed -i -e 's/\r$//' /app/entrypoint.sh &&
            chmod +x /app/entrypoint.sh &&
            sed -i 's/^clickhouse_ip_address = .*/clickhouse_ip_address = clickhouse-service.spark-app.svc.cluster.local/' ./conf/spark.ini &&
            cat ./conf/spark.ini &&
            /app/entrypoint.sh
        ports:
        - containerPort: 4040
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse-service.spark-app.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: spark-app
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
