apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: zarus03/model:latest
        resources:
          requests:
            cpu: "1300m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        command: ["/bin/sh", "-c"]
        args:
          - /app/entrypoint.sh
        ports:
        - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: spark-app
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
