#!/bin/bash

echo "Dropping table openfoodfacts if exists"
clickhouse-client --progress --verbose --query="DROP TABLE IF EXISTS openfoodfacts"

echo "Dropping table openfoodfacts_proc if exists"
clickhouse-client --progress --verbose --query="DROP TABLE IF EXISTS openfoodfacts_proc"

echo "Creating table"
clickhouse-client --progress --verbose --query="
CREATE TABLE openfoodfacts (
  code String,
  url Nullable(String),
  creator Nullable(String),
  created_t Nullable(String),
  created_datetime Nullable(String),
  last_modified_t Nullable(String),
  last_modified_datetime Nullable(String),
  last_modified_by Nullable(String),
  last_updated_t Nullable(String),
  last_updated_datetime Nullable(String),
  product_name Nullable(String),
  abbreviated_product_name Nullable(String),
  generic_name Nullable(String),
  quantity Nullable(String),
  packaging Nullable(String),
  packaging_tags Nullable(String),
  packaging_en Nullable(String),
  packaging_text Nullable(String),
  brands Nullable(String),
  brands_tags Nullable(String),
  brands_en Nullable(String),
  categories Nullable(String),
  categories_tags Nullable(String),
  categories_en Nullable(String),
  origins Nullable(String),
  origins_tags Nullable(String),
  origins_en Nullable(String),
  manufacturing_places Nullable(String),
  manufacturing_places_tags Nullable(String),
  labels Nullable(String),
  labels_tags Nullable(String),
  labels_en Nullable(String),
  emb_codes Nullable(String),
  emb_codes_tags Nullable(String),
  first_packaging_code_geo Nullable(String),
  cities Nullable(String),
  cities_tags Nullable(String),
  purchase_places Nullable(String),
  stores Nullable(String),
  countries Nullable(String),
  countries_tags Nullable(String),
  countries_en Nullable(String),
  ingredients_text Nullable(String),
  ingredients_tags Nullable(String),
  ingredients_analysis_tags Nullable(String),
  allergens Nullable(String),
  allergens_en Nullable(String),
  traces Nullable(String),
  traces_tags Nullable(String),
  traces_en Nullable(String),
  serving_size Nullable(String),
  serving_quantity Nullable(String),
  no_nutrition_data Nullable(String),
  additives_n Nullable(String),
  additives Nullable(String),
  additives_tags Nullable(String),
  additives_en Nullable(String),
  nutriscore_score Nullable(String),
  nutriscore_grade Nullable(String),
  nova_group Nullable(String),
  pnns_groups_1 Nullable(String),
  pnns_groups_2 Nullable(String),
  food_groups Nullable(String),
  food_groups_tags Nullable(String),
  food_groups_en Nullable(String),
  states Nullable(String),
  states_tags Nullable(String),
  states_en Nullable(String),
  brand_owner Nullable(String),
  environmental_score_score Nullable(String),
  environmental_score_grade Nullable(String),
  nutrient_levels_tags Nullable(String),
  product_quantity Nullable(String),
  owner Nullable(String),
  data_quality_errors_tags Nullable(String),
  unique_scans_n Nullable(String),
  popularity_tags Nullable(String),
  completeness Nullable(String),
  last_image_t Nullable(String),
  last_image_datetime Nullable(String),
  main_category Nullable(String),
  main_category_en Nullable(String),
  image_url Nullable(String),
  image_small_url Nullable(String),
  image_ingredients_url Nullable(String),
  image_ingredients_small_url Nullable(String),
  image_nutrition_url Nullable(String),
  image_nutrition_small_url Nullable(String),
  energy_kj_100g Nullable(String),
  energy_kcal_100g Nullable(String),
  energy_100g Nullable(String),
  energy_from_fat_100g Nullable(String),
  fat_100g Nullable(String),
  saturated_fat_100g Nullable(String),
  butyric_acid_100g Nullable(String),
  caproic_acid_100g Nullable(String),
  caprylic_acid_100g Nullable(String),
  capric_acid_100g Nullable(String),
  lauric_acid_100g Nullable(String),
  myristic_acid_100g Nullable(String),
  palmitic_acid_100g Nullable(String),
  stearic_acid_100g Nullable(String),
  arachidic_acid_100g Nullable(String),
  behenic_acid_100g Nullable(String),
  lignoceric_acid_100g Nullable(String),
  cerotic_acid_100g Nullable(String),
  montanic_acid_100g Nullable(String),
  melissic_acid_100g Nullable(String),
  unsaturated_fat_100g Nullable(String),
  monounsaturated_fat_100g Nullable(String),
  omega_9_fat_100g Nullable(String),
  polyunsaturated_fat_100g Nullable(String),
  omega_3_fat_100g Nullable(String),
  omega_6_fat_100g Nullable(String),
  alpha_linolenic_acid_100g Nullable(String),
  eicosapentaenoic_acid_100g Nullable(String),
  docosahexaenoic_acid_100g Nullable(String),
  linoleic_acid_100g Nullable(String),
  arachidonic_acid_100g Nullable(String),
  gamma_linolenic_acid_100g Nullable(String),
  dihomo_gamma_linolenic_acid_100g Nullable(String),
  oleic_acid_100g Nullable(String),
  elaidic_acid_100g Nullable(String),
  gondoic_acid_100g Nullable(String),
  mead_acid_100g Nullable(String),
  erucic_acid_100g Nullable(String),
  nervonic_acid_100g Nullable(String),
  trans_fat_100g Nullable(String),
  cholesterol_100g Nullable(String),
  carbohydrates_100g Nullable(String),
  sugars_100g Nullable(String),
  added_sugars_100g Nullable(String),
  sucrose_100g Nullable(String),
  glucose_100g Nullable(String),
  fructose_100g Nullable(String),
  lactose_100g Nullable(String),
  maltose_100g Nullable(String),
  maltodextrins_100g Nullable(String),
  starch_100g Nullable(String),
  polyols_100g Nullable(String),
  erythritol_100g Nullable(String),
  fiber_100g Nullable(String),
  soluble_fiber_100g Nullable(String),
  insoluble_fiber_100g Nullable(String),
  proteins_100g Nullable(String),
  casein_100g Nullable(String),
  serum_proteins_100g Nullable(String),
  nucleotides_100g Nullable(String),
  salt_100g Nullable(String),
  added_salt_100g Nullable(String),
  sodium_100g Nullable(String),
  alcohol_100g Nullable(String),
  vitamin_a_100g Nullable(String),
  beta_carotene_100g Nullable(String),
  vitamin_d_100g Nullable(String),
  vitamin_e_100g Nullable(String),
  vitamin_k_100g Nullable(String),
  vitamin_c_100g Nullable(String),
  vitamin_b1_100g Nullable(String),
  vitamin_b2_100g Nullable(String),
  vitamin_pp_100g Nullable(String),
  vitamin_b6_100g Nullable(String),
  vitamin_b9_100g Nullable(String),
  folates_100g Nullable(String),
  vitamin_b12_100g Nullable(String),
  biotin_100g Nullable(String),
  pantothenic_acid_100g Nullable(String),
  silica_100g Nullable(String),
  bicarbonate_100g Nullable(String),
  potassium_100g Nullable(String),
  chloride_100g Nullable(String),
  calcium_100g Nullable(String),
  phosphorus_100g Nullable(String),
  iron_100g Nullable(String),
  magnesium_100g Nullable(String),
  zinc_100g Nullable(String),
  copper_100g Nullable(String),
  manganese_100g Nullable(String),
  fluoride_100g Nullable(String),
  selenium_100g Nullable(String),
  chromium_100g Nullable(String),
  molybdenum_100g Nullable(String),
  iodine_100g Nullable(String),
  caffeine_100g Nullable(String),
  taurine_100g Nullable(String),
  ph_100g Nullable(String),
  fruits_vegetables_nuts_100g Nullable(String),
  fruits_vegetables_nuts_dried_100g Nullable(String),
  fruits_vegetables_nuts_estimate_100g Nullable(String),
  fruits_vegetables_nuts_estimate_from_ingredients_100g Nullable(String),
  collagen_meat_protein_ratio_100g Nullable(String),
  cocoa_100g Nullable(String),
  chlorophyl_100g Nullable(String),
  carbon_footprint_100g Nullable(String),
  carbon_footprint_from_meat_or_fish_100g Nullable(String),
  nutrition_score_fr_100g Nullable(String),
  nutrition_score_uk_100g Nullable(String),
  glycemic_index_100g Nullable(String),
  water_hardness_100g Nullable(String),
  choline_100g Nullable(String),
  phylloquinone_100g Nullable(String),
  beta_glucan_100g Nullable(String),
  inositol_100g Nullable(String),
  carnitine_100g Nullable(String),
  sulphate_100g Nullable(String),
  nitrate_100g Nullable(String),
  acidity_100g Nullable(String)
)
ENGINE = MergeTree()
ORDER BY (code)
PRIMARY KEY (code)"

echo "Running ClickHouse import with statistics..."
clickhouse-client --progress --verbose \
  --query="
SET input_format_allow_errors_num = 1000;
SET input_format_tsv_empty_as_default = 1;
INSERT INTO openfoodfacts 
SELECT * FROM file(
  '/var/lib/clickhouse/user_files/sparkdata/en.openfoodfacts.org.products.csv', 
  'TSVWithNames'
) LIMIT 5000;"

echo -e "\nAdding prediction column..."
clickhouse-client --progress --verbose --query="
ALTER TABLE openfoodfacts 
ADD COLUMN prediction Nullable(String) DEFAULT NULL;"